name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  python-ci:
    permissions:
      contents: read
      security-events: write
    uses: vyzii/central-cicd-library/.github/workflows/python-ci.yaml@main

      